server:
  port: 8500
spring:
  application:
    name: spmall-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 8.130.12.102:8848
        username: nacos
        password: nacos
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"
            # 允许请求中携带的头信息
            allowedHeaders: "*"
            # 运行跨域的请求方式
            allowedMethods: "*"
            # 跨域检测的有效期,单位s
            maxAge: 36000
      routes:
        - id: product-service
          uri: lb://service-product
          predicates:
            - Path=/*/product/**
        - id: user-service
          uri: lb://service-user
          predicates:
            - Path=/*/user/**
        - id: service-cart
          uri: lb://service-cart
          predicates:
            - Path=/api/order/cart/**
        - id: service-order
          uri: lb://service-order
          predicates:
            - Path=/api/order/orderInfo/**
  data:
    redis:
      port: 6381
      host: 8.130.12.102