# 配置服务端口号
server:
  port: 8501

# 配置数据库连接信息
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://8.130.12.102:3306/db_spmall?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 111
    hikari:
      connection-timeout: 30000
  # Redis的相关配置
  data:
    redis:
      host: 8.130.12.102
      port: 6381
  cache:
    type: redis
#  password: 1234

# mybatis的配置
mybatis:
  config-location: classpath:/mybatis-config.xml
  mapper-locations: classpath:/mapper/*.xml
    #configuration:
  # cache-enabled: true

spmall:
  auth:
    no-confirm-urls:
      - /admin/system/index/login
      - /admin/system/index/generateValidateCode
      - /admin/system/index/logout
  minio:
    endpointUrl: http://8.130.12.102:9000
    accessKey: minioadmin
    secretKey: admin121148
    bucketName: spmall-bucket


sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: nicego
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: true
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: uuid
  # 是否输出操作日志
  is-log: true
  #token有效期，默认30天，现在是半小时
  active-timeout: 3600
  timeout: 3600