server:
  port: 8513

spring:
  application:
    name: service-cart
  cloud:
    nacos:
      discovery:
        server-addr: 8.130.12.102:8848
        username: nacos
        password: nacos
  data:
    redis:
      host: 8.130.12.102
      port: 6381