server:
  port: 8512

spring:
  application:
    name: service-user
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacos
    sentinel:
      log:
        dir: E:\Java Project\Personal\ycheng-spmall-parent\spmall-service\service-user\log
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://8.130.12.102:3306/db_spmall?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=true
    username: root
    password: 111
  data:
    redis:
      host: 8.130.12.102
      port: 6381

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:/mapper/*.xml

http-client:
  max-total: 100
  default-max-per-route: 100
  connect-timeout: 2000
  connection-request: 5000
  socket-timeout: 2000
  validate-after-inactivity: 2000

sms-user:
  app-code: ef2f1fcd234f451297354d94d07776ad
  app-secret: 9bbBfh13JmKQIYvW0FKtUg5WIM2bgZM8
  app-key: 204517503
logging:
  config: classpath:logback-spring.xml